### ISSUE TITLE
Left label width should expand if played long time.

### ISSUE THREAD

**Issue by r-plus** [bizz84/MVMediaSlider#2]
Left label width should expand if played long time.
Or above position than center view.

![fullsizerender](https://cloud.githubusercontent.com/assets/425216/17460668/bf5f60fe-5cab-11e6-991e-6c2d49b5a31b.jpg)

**Comment by bizz84** [comment]
What font size are you using? The demo project is set up to use System Font Size 14.0 and with that it should display durations up to 99.59 without cropping.

I understand that this is not a robust solution as increasing the font size in the configuration or in Accessibility will break. Once I get the time to fix this properly, I'll do so.

**Comment by r-plus** [comment]
I'm not changed that font.
I also confirmed issue on demo project.

![simulator screen shot 2016 08 13 20 18 49](https://cloud.githubusercontent.com/assets/425216/17642896/3bb04d9e-6193-11e6-8746-054d60421021.png)

**Comment by r-plus** [comment]
I just send a pull request I think fix this issue.

**Comment by bizz84** [comment]
Thanks for the fix, much appreciated!
